site:
  title: Red Hat OpenStack Services on OpenShift Architecture
  start_page: rhoso-arch::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
