= Summary

In this chapter, you learned:

* An OpenStack control plane is composed of multiple user-facing and internal infrastructure serviced which run as containers on Red Hat OpenShift.

* OpenStack user-facing services provide the usual OpenStack services and their APIs, such as Nova, Cinder, Neutron, Keystone, etc.

* OpenStack internal infrastructure services provide storage, connectivity, and other capabilities for OpenStack user-facing services.

* Red Hat OpenStack Services on OpenShift includes three main internal infrastructure services: Galera, which clusters MariaDB relational databases; RabbitMQ, which provides AMQP messaging; and OVN, which provides a software-defined network layer.

* Each OpenStack service may be composed of multiple components, which communicate with each other using AMQP, and store data (API Resource instances) on MariaDB. Components running on compute nodes never access MariaDB directly, but they access the HTTP APIs of other OpenStack services and the AMQP messages of other components of the same service.

* OpenStack Administrators must use Kubernetes APIs and custom resources the from OpenStack add-on operator to manage their OpenStack services, both user-facing and internal infrastructure, and for that they must use either the OpenShift client or the OpenShift web console.

* Components of OpenStack services which run on OpenShift must use Kubernetes storage and network capabilities, but they must also access external storage and network resources, not managed by Kubernetes, which are required by RHEL compute nodes.
