= Answers to the Quiz

WARNING: Work In Progress

== Quiz: OpenStack Services as OpenShift Workloads

1. Given the following description of a component of an OpenStack service, which Kubernetes workload controller best fits its needs?
+
[quote]
____
Each node in an OVN virtual network must run an OVN controller, which creates Geneve tunnels between those nodes to encapsulate and forward network packets belonging to OVN virtual networks. With Red Hat OpenStack Services on OpenShift, all OpenShift and OpenStack compute nodes must run an OpenStack OVN controller.
____

* [ ] Replica Set +
_Incorrect: replica sets are not constrained by number of hosts._

* [ ] Deployment +
_Incorrect: deployments are not constrained by number of hosts._

* [ ] Job +
_Incorrect: jobs would run only one OVN controller for all hosts and only one time instead of continuously._

* [ ] Cron Job +
_Incorrect: cron jobs would run only one OVN controller for all hosts, at regular intervals, instead of continuously._

* [ ] Stateful Set +
_Incorrect: stateful sets are not constrained by number of hosts._

* [x] *Daemon Set* +
_Correct: Daemon Sets run one Pod per Kubernetes cluster node._

2. Given the following description of a component of an OpenStack service, which Kubernetes workload controller best fits its needs?
+
[quote]
____
RabbitMQ nodes and clusters store information that can be thought of schema, metadata or topology. These definitions are replicated across all cluster nodes.

Each node stores messages for the queues that have their leader replica hosted on that node. Messages can be replicated between nodes if a replicated queue type with multiple replicas is used.
____

* [ ] Replica Set +
_Incorrect: RabbitMQ nodes are not stateless, each one must know for which queues it is the leader replica._

* [ ] Deployment +
_Incorrect: RabbitMQ nodes are not stateless, each one must know for which queues it is the leader replica, as it may contain copies of data for which it is not the replica leader._

* [ ] Job +
_Incorrect: As a messaging server, RabbitMQ must run continously instead of only once._

* [ ] Cron Job +
_Incorrect: As a messaging server, RabbitMQ must run continously instead of periodically._

* [x] *Stateful Set* +
_Correct: A stateful set enables each RabbitMQ node to retain its identity and know if its the leader replica for any queues stored on their persistent storage._

* [ ] Daemon Set +
_Incorrect: There is no requirement of running one RabbitMQ instance per Kubernetes cluster node._

3. Given the following description of a component of an OpenStack service, which Kubernetes workload controller best fits its needs?
+
[quote]
____
Horizon is essentially a stateless application, with the caveat that session information could be considered stateful. The use of signed cookies places the full contents of the session state into an HTTP header rather than relying on an in-memory cache or database tier to provide session state persistence.
____

* [ ] Replica Set +
_Incorrect: Almost all times a Replica Set would fit, a Deployment is a better alternative._

* [x] *Deployment* +
_Correct: Horizon is completely stateless when configured to store session data in an HTTP cookie._

* [ ] Job +
_Incorrect: Horizon must run continuously instead of only once._

* [ ] Cron Job +
_Incorrect: Horizon must run continuously instead of at a recurring schedule._

* [ ] Stateful Set +
_Incorrect: There is no requirement of retaining state or identity of individual Horizon instances._

* [ ] Daemon Set +
_Incorrect: There is no requirement of running one Horizon pod per OpenShift cluster node._

4. Given the following description of a component of an OpenStack service, which Kubernetes workload controller best fits its needs?
+
[quote]
____
When you create a Data Plane Deployment resource, the External Data Plane Mangement Operator runs one Ansible playbook for each Data Plane Service configured for each Node Set of the data plane, using a custom Ansible Execution Environment container image. Each playbook runs to completion, and when all playbooks finish, the data plane and all its compute nodes should be fully configured for their OpenStack cluster. To perform any change to compute nodes, an OpenStack Administrator must create a new Data Plane Deployment resource, which triggers a new execution of all Ansible playbooks.
____

* [ ] Replica Set +
_Incorrect: Data Plane Service playbooks are not a continuoulsy running application._

* [ ] Deployment +
_Incorrect: Data Plane Service playbooks are not a continuoulsy running application._

* [x] *Job* +
_Correct: Data Plane Service playbooks runs only once. OpenStack Administrators must explicilty trigger new executions of those playbooks._

* [ ] Cron Job +
_Incorrect: Data Plane Service playbooks are not a recurring application. OpenStack Administrators must explicilty trigger each execution of all playbooks._

* [ ] Stateful Set +
_Incorrect: Data Plane Service playbooks are not a continuoulsy running application._

* [ ] Daemon Set
_Incorrect: Data Plane Service playbooks do not need to run once per OpenShift cluster node, but once for each OpenStack cluster compute node. Ansible deals with that using its host inventory mechanism._
