:time_estimate: 1

= Answers to the Quiz

WARNING: Work In Progress

== Kubernetes Networking for OpenStack Services

1. Why does OpenStack clusters typically require multiple, isolated networks?

* [ ] Because OpenStack services cannot use Kubernetes networking features to connect to RHEL compute nodes. +
_Incorrect: Kubernetes provides multiple mechanisms to enable connectivity between applications running as containers and applications outside of Kubernetes clusters._

* [ ] Because multiple OpenStack services listen to the same TCP ports and each must bind to different IP addresses. +
_Incorrect: OpenStack services can be configured to use different TCP ports on the same IP addresses (or also different IP addresses, if you prefer) and Keystone enables clients and other services to discover those ports and addresses._

* [x] *Because OpenStack services and other IT infrastructure present performance, reliability, and security concerns related to network traffic.* +
_Correct: General data center concerns about using network capacity and seggregating traffic drive isolated network designs. It is not anything required by OpenStack itself._

* [ ] Because Both OpenStack Neutron and OpenShift use the OVN software-defined networking layer and they conflict with each other. +
_Correct: While conflicts among the OVN instances from OpenShift and Openstack influence an isolated network design, it is not the main reason. OpenStack would still use multiple isolated networks without OpenShift and without OVN._

2. The reference OpenStack network scenario contains five networks: ctlplane, internalapi, tenant, storage, and external. On which of those networks there is application traffic?

* [ ] ctlplane +
_Incorrect: The ctlplane network has traffic between an components of OpenStack running in the control and data planes._

* [ ] internalapi +
_Incorrect: The ctlplane network has traffic between an components of OpenStack running in the control and data planes._

* [x] *tenant* +
_Correct: The tenant network has traffic between applications running as VMs inside an OpenStack cluster._

* [x] *storage* +
_Correct: The storage network has traffic between applications and storage backends._

* [x] *external* +
_Correct: The external network has traffic between applications and their end users or applications inside and outside an OpenStack cluster._

3. Which of the following are reasons for Pods in Kubernetes communications with other Pods through Kubernetes Services instead of directly?

* [x] *Pods do not have a stable IP address and Services provide such stable addresses.* +
_Correct: While the IP address of a pod does not change during the life of a Pod, pods are supposed to be short-lived, and replacement Pods created by a workload controllers will get new IP addresses._

* [x] *Pods are ephemeral and might be replaced by new pods at any time.* +
_Correct: Kubernetes workload controllers do not try to keep a Pod running, nor try to restart terminated Pods. They just create new Pods to take the place of terminated Pods, and those new Pods get new IP addresses._

* [ ] Pods cannot connect directly to each other because of Kubernetes Network Policies. +
_Incorrect: It is true that you can block communication between Pods by using Network Policies, but them communication would be blocked from Services also._

* [x] *Pods do not get DNS local names, while Services do*. +
_Correct: Kubernetes internal DNS does not assign names to individual Pods, but does assign names to individual services._

* [x] *Services perform load balancing among replica Pods from the same workload.* +
_Correct: Services load balance among all pods (or a subset of pods) of the same workload controller._

4. How do Kubernetes Pods connect to services and applications outside of their Kubernetes cluster?

* [ ] By connecting to an Egress Service created for the application namespace. +
_Incorrect: While OpenShift enables the use of Egress Services to provide well knwon virtual IP addresses to applications, they are not required and all Pods have network connectivity with outside their cluster._

* [ ] By connecting to a secondary network attached to the Pod. +
_Incorrect: While OpenShift enables the use secondary networks to provide connectivity to multiple isolated networks, they are not required and all Pods have network connectivity with outside their cluster, using the Kubernetes primary network._

* [x] *By relying on Network Address Transation (NAT) performed by Kubernetes on all cluster nodes.* +
_Correct: Kubernetes cluster nodes perform Source Network Address Transation (SNAT) on all packets send by Pods to outside of the cluster, so those packets seem to originate from the node instead of from the Kubernetes cluster network._

* [ ] By relying on a Network Gateway Router created for the application namespace. +
_Incorrect: Contratry to most IaaS cloud platforms, including OpenStack, which require the configuration of Network Routers, NAT Gateways, and similar connectivity gateways between internal and external networks, Kubernetes performs NAT for all Pods._

5. A video processing application supports both web clients using HTTP and video devices using RTSP. Knowing that RTSP is not based on HTTP and is not compatible with TLS, which of the following Kubernetes API resource types can provide connectivity to clients of that video processing application?

* [x] *Route* +
_Correct: OpenShift Routes provide reverse HTTP proxying and support web clientes of the video processing application._

* [x] *Ingress* +
_Correct: Kubernetes Ingress provide reverse HTTP proxying and support web clientes of the video processing application._

* [ ] Service of type Cluster IP +
_Incorrect: Kubernetes Services of type Cluster IP only provide connectivity with other Pods inside the same Kubernetes cluster and do not provide conenctivity with external web clientes nor external video devices._

* [x] *Service of type Load Balancer* +
_Correct: Kubernetes Services of type Load Balancer enable ingress connections using any IP-based protocol and would support both external web clients and external video devices._

* [x] *Network Attachment Definition* +
_Correct: Multus Network Attachment Definitions define secondaty networks to which any Pods of the same namespace can attach and enable bi-directional connections using any IP-based protocol and would support both external web clients and external video devices._

* [ ] Network Node Configuration Policy +
_Incorrect: NMState Network Node Configuration Policies only configure network interfaces in OpenShift cluster nodes and do not attach those interfaces to Pods. You also need Multus Network Attachment Definitions to define secondary networks based on those interfaces._

6. Red Hat OpenStack Services on OpenShift uses OpenShift Routes, enabled by the OpenShift Ingress cluster operator, for the following communication patterns on the specificed reference networks:

* [ ] Public API end points of OpenStack Services over the external network. +
_Incorrect: The referente network scenario exposes public OpenStack API endpoints on the Kubernetes primary network because OpenShift Routes can only work with that network._

* [x] *Public API end points of OpenStack Services over the Kubernetes primary network.* +
_Correct: Red Hat OpenStack Services on OpenShift uses OpenShift Routes to expose all public facing OpenStack APIs and only exposes them over the Kubernetes primary network._

* [ ] Private API end points of OpenStack Services over the ctlplane network. +
_Incorrect: The referente network scenario exposes private OpenStack API endpoints on the internalapi network. Anyway, Routes would not work because they can only attach to the Kubernetes primary network._

* [ ] Private API end points of OpenStack Services over the internalapi network. +
_Incorrect: Routes would not work for private API endpoints because the reference network scenario uses the internalapi network and routes can only attach tot he Kubernetes primary network._

* [ ] AMQP Messaging over the ctlplane network. +
_Incorrect: The reference network scenario uses the internalapi network for AMQP traffic. Anyway, OpenShift Routes cannot support non-HTTP protocols such as AMQP._

* [ ] AMQP Messaging over the internalapi network. +
_Incorrect: OpenShift Routes cannot support non-HTTP protocols such as AMQP._

* [ ] SSH management of compute nodes over the ctlplane network. +
_Incorrect: OpenShift Routes cannot support non-HTTP protocols such as SSH. Anmyway, Routes provides ingress traffic to Pods, while SSH connections are eggress connections from Pods to RHEL compute nodes._

* [ ] SSH management of compute nodes over the internalapi network. +
_Incorrect: OpenStack performs SSH management of compute nodes over the ctlplane network. Anyway, OpenShift Routes cannot support non-HTTP protocols such as SSH._

7. Red Hat OpenStack Services on OpenShift uses Kubernetes Services of type Load Balancer, enabled by the MetalLB add-on operator, for the following communication patterns on the specificed reference networks:

* [ ] Public API end points of OpenStack Services over the external network. +
_Incorrect: The reference network scenario exposes public APIs on the kubernetes primary network. Anyway, OpenStack uses OpenShift Routes instead of Services._

* [ ] Public API end points of OpenStack Services over the Kubernetes primary network. +
_Incorrect: OpenStack uses OpenShift Routes as a better alternative than Services for exposing HTTP over the Kubernetes primary network._

* [ ] Private API end points of OpenStack Services over the ctlplane network. +
_Incorrect: The reference network scenario exposes private APIs on the internalapi network._

* [x] *Private API end points of OpenStack Services over the internalapi network.* +
_Correct: OpenStack uses Kubernetes Services as external load balancers for private APIs over HTTP because you cannot expose Routes or Ingress on secondary networks._

* [ ] AMQP Messaging over the ctlplane network. +
_Incorrect: The reference network scenario exposes AMQP messaging on the internalapi network._

* [x] *AMQP Messaging over the internalapi network.* +
_Correct: OpenStack uses Kubernetes Services as external load balancers for AMQP messaging and MetalLB enables exposing Services with VIPs on secondary networks._

* [ ] SSH management of compute nodes over the ctlplane network. +
_Incorrect: Services provides ingress traffic to Pods, while SSH connections are eggress connections from Pods to RHEL compute nodes._

* [ ] SSH management of compute nodes over the internalapi network. +
_Incorrect: OpenStack performs SSH management of compute nodes over the ctlplane network. Anyway, Services provide only ingress traffic to Pods, while SSH connections are eggress traffic._

8. Red Hat OpenStack Services on OpenShift uses secondary networks, enabled by Multus, for the following communication patterns on the specificed reference networks:

* [ ] Public API end points of OpenStack Services over the external network. +
_Incorrect: OpenStack uses Routes for public API endpoints, and only on the Kubernetes primary network._

* [ ] Public API end points of OpenStack Services over the Kubernetes primary network. +
_Incorrect: OpenStack uses Routes for public API endpoints and there is no need to configure Multus for the Kubernetes primary network because it is not a secondary network._

* [ ] Private API end points of OpenStack Services over the ctlplane network. +
_Incorrect: The reference network scenario uses the internalapi network for private API end points. Anyway, MetalLB does not require its VIPs to belong to networks also availabe as secondary networks to Pods._

* [ ] Private API end points of OpenStack Services over the internalapi network. +
_Incorrect: MetalLB can attach Kubernetes Services to virtual IPs on any network and does not require those networks to be availabe as secondary networks to Pods._

* [ ] AMQP Messaging over the ctlplane network. +
_Incorrect: The reference network scenario uses the internalapi network AMQP messaging. Anyway, MetalLB does not require its VIPs to belong to networks also availabe as secondary networks to Pods._

* [ ] AMQP Messaging over the internalapi network. +
_Incorrect: MetalLB can attach Kubernetes Services to virtual IPs on any network and does not require those networks to be availabe as secondary networks to Pods._

* [x] *SSH management of compute nodes over the ctlplane network.* +
_Correct: Routes and Services would not be sufficient to provide egress connectivity with secondary networks, so Ansible pods must attach directly to the ctlplane network as a secondary network._

* [ ] SSH management of compute nodes over the internalapi network. +
_Incorrect: The reference network scenario uses the ctlplane network to open SSH sessions to RHEL compute nodes._
